language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t vlohvyniuk/docker-react -f Dockerfile.dev .
  

script:
  - docker run -e CI=true vlohvyniuk/docker-react npm run test